package demo.client.shared;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Expense implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "EXPENSE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "EXPENSE_ID_SEQ", name = "EXPENSE_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Subject")
	@javax.validation.constraints.NotNull
	@org.hibernate.validator.constraints.NotEmpty
	private java.lang.String subject;

	@org.kie.api.definition.type.Label("Price")
	@javax.validation.constraints.Min(0L)
	@javax.validation.constraints.Max(10000L)
	private java.lang.Double price;

	@org.kie.api.definition.type.Label("Date")
	@javax.validation.constraints.NotNull
	private java.util.Date date;

	public Expense() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public Expense(java.lang.Long id, java.lang.String subject,
			java.lang.Double price, java.util.Date date) {
		this.id = id;
		this.subject = subject;
		this.price = price;
		this.date = date;
	}

}